CREATE TABLE fix_task_pre_execution_decision (
    id varchar(36) not null primary key,
    task_id varchar(36) not null,
    source varchar(32) not null,
    final_decision varchar(32) not null,
    safety_allowed boolean not null,
    safety_reason text not null,
    safety_category varchar(64) not null,
    active_task_allowed boolean not null,
    active_task_reason text not null,
    active_task_category varchar(64) not null,
    quarantine_allowed boolean not null,
    quarantine_reason text not null,
    quarantine_category varchar(64) not null,
    rate_limit_allowed boolean not null,
    rate_limit_reason text not null,
    rate_limit_category varchar(64) not null,
    trigger_intent_allowed boolean not null,
    trigger_intent_reason text not null,
    trigger_intent_category varchar(64) not null,
    issue_context_loaded boolean not null,
    created_at timestamp(6) not null,
    INDEX idx_fix_task_pre_execution_decision_task_created (task_id, created_at)
);
