CREATE TABLE fix_task_evidence_acceptance_certificate_archive (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    status VARCHAR(32) NOT NULL,
    certified BOOLEAN NOT NULL,
    summary VARCHAR(1024) NOT NULL,
    next_action VARCHAR(1024) NOT NULL,
    archive_count INT NOT NULL,
    latest_closeout_archive_id VARCHAR(36),
    latest_evidence_archive_id VARCHAR(36),
    latest_delivery_receipt_id VARCHAR(36),
    latest_task_id VARCHAR(64),
    latest_pull_request_url VARCHAR(512),
    latest_delivery_target VARCHAR(512),
    latest_delivery_channel VARCHAR(128),
    delivery_receipt_freshness VARCHAR(32) NOT NULL,
    latest_archived_at TIMESTAMP(6),
    generated_at TIMESTAMP(6) NOT NULL,
    archived_at TIMESTAMP(6) NOT NULL,
    download_actions_json MEDIUMTEXT NOT NULL,
    report MEDIUMTEXT NOT NULL,
    INDEX idx_fix_task_evidence_certificate_archived (archived_at),
    INDEX idx_fix_task_evidence_certificate_closeout (latest_closeout_archive_id, archived_at),
    INDEX idx_fix_task_evidence_certificate_task (latest_task_id, archived_at)
);
