CREATE TABLE external_exposure_closeout_archive (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    status VARCHAR(32) NOT NULL,
    closeout_ready BOOLEAN NOT NULL,
    summary VARCHAR(1024) NOT NULL,
    next_action VARCHAR(1024) NOT NULL,
    latest_session_id VARCHAR(36) NULL,
    latest_session_status VARCHAR(32) NULL,
    public_url VARCHAR(2048) NULL,
    webhook_url VARCHAR(2048) NULL,
    purpose VARCHAR(1024) NULL,
    operator VARCHAR(255) NULL,
    started_at TIMESTAMP(6) NULL,
    closed_by VARCHAR(255) NULL,
    closed_at TIMESTAMP(6) NULL,
    close_notes TEXT NULL,
    linked_readiness_archive_id VARCHAR(36) NULL,
    handoff_status VARCHAR(32) NULL,
    archive_freshness VARCHAR(32) NULL,
    ready_count INT NOT NULL,
    needs_attention_count INT NOT NULL,
    blocked_count INT NOT NULL,
    total_count INT NOT NULL,
    evidence_notes TEXT NOT NULL,
    next_actions TEXT NOT NULL,
    download_actions TEXT NOT NULL,
    side_effect_contract VARCHAR(1024) NOT NULL,
    generated_at TIMESTAMP(6) NOT NULL,
    archived_at TIMESTAMP(6) NOT NULL,
    report MEDIUMTEXT NOT NULL,
    INDEX idx_external_exposure_closeout_archive_archived (archived_at),
    INDEX idx_external_exposure_closeout_archive_status_archived (status, archived_at),
    INDEX idx_external_exposure_closeout_archive_session (latest_session_id)
);
