package io.patchpilot.backend.demo.domain;

import io.patchpilot.backend.configuration.ConfigurationSummaryVo;
import io.patchpilot.backend.github.credential.domain.GitHubWebhookSetupReadinessVo;
import io.patchpilot.backend.github.webhook.domain.WebhookDeliveryDiagnosticVo;
import io.patchpilot.backend.safety.domain.RejectedTriggerAuditSummaryVo;
import io.patchpilot.backend.task.domain.vo.FixTaskQueueSummaryVo;
import io.patchpilot.backend.task.domain.vo.FixTaskVo;

import java.time.Instant;
import java.util.List;

public record DemoEvidenceBundleVo(
        DemoReadinessStatus status,
        String summary,
        DemoEvidenceBundleSummaryVo summaryCounts,
        DemoReadinessVo readiness,
        DemoSmokeChecklistVo smokeChecklist,
        ConfigurationSummaryVo configuration,
        DemoAdapterFixtureEvidenceVo adapterFixtures,
        FixTaskQueueSummaryVo queueSummary,
        FixTaskVo recentTask,
        String recentPullRequestUrl,
        GitHubWebhookSetupReadinessVo webhookSetupReadiness,
        WebhookDeliveryDiagnosticVo latestWebhookDelivery,
        List<WebhookDeliveryDiagnosticVo> recentWebhookDeliveries,
        RejectedTriggerAuditSummaryVo rejectedTriggerSummary,
        long activeQuarantineCount,
        DemoReadinessStatus handoffShareChecklistStatus,
        String handoffShareChecklistSummary,
        String handoffShareChecklistNextAction,
        DemoReadinessStatus handoffShareCenterStatus,
        String handoffShareCenterSummary,
        String handoffShareCenterNextAction,
        List<String> handoffShareCenterDownloadActions,
        boolean handoffShareDeliveryReceiptRecorded,
        String handoffShareLatestDeliveryReceiptId,
        String handoffShareLatestDeliveryTarget,
        String handoffShareLatestDeliveryChannel,
        String handoffShareLatestDeliveredAt,
        String handoffShareDeliveryReceiptFreshness,
        boolean handoffShareDeliveryReceiptFresh,
        String handoffShareDeliveryReceiptFreshnessSummary,
        DemoReadinessStatus handoffFinalizationStatus,
        boolean handoffFinalized,
        String handoffFinalizationSummary,
        String handoffFinalizationNextAction,
        String handoffFinalizationDeliveryReceiptFreshness,
        boolean handoffFinalizationDeliveryReceiptFresh,
        String handoffFinalizationLatestDeliveryReceiptId,
        Instant generatedAt,
        List<String> nextActions
) {
    public DemoEvidenceBundleVo(
            DemoReadinessStatus status,
            String summary,
            DemoEvidenceBundleSummaryVo summaryCounts,
            DemoReadinessVo readiness,
            DemoSmokeChecklistVo smokeChecklist,
            ConfigurationSummaryVo configuration,
            DemoAdapterFixtureEvidenceVo adapterFixtures,
            FixTaskQueueSummaryVo queueSummary,
            FixTaskVo recentTask,
            String recentPullRequestUrl,
            GitHubWebhookSetupReadinessVo webhookSetupReadiness,
            WebhookDeliveryDiagnosticVo latestWebhookDelivery,
            List<WebhookDeliveryDiagnosticVo> recentWebhookDeliveries,
            RejectedTriggerAuditSummaryVo rejectedTriggerSummary,
            long activeQuarantineCount,
            DemoReadinessStatus handoffShareChecklistStatus,
            String handoffShareChecklistSummary,
            String handoffShareChecklistNextAction,
            DemoReadinessStatus handoffShareCenterStatus,
            String handoffShareCenterSummary,
            String handoffShareCenterNextAction,
            List<String> handoffShareCenterDownloadActions,
            Instant generatedAt,
            List<String> nextActions
    ) {
        this(
                status,
                summary,
                summaryCounts,
                readiness,
                smokeChecklist,
                configuration,
                adapterFixtures,
                queueSummary,
                recentTask,
                recentPullRequestUrl,
                webhookSetupReadiness,
                latestWebhookDelivery,
                recentWebhookDeliveries,
                rejectedTriggerSummary,
                activeQuarantineCount,
                handoffShareChecklistStatus,
                handoffShareChecklistSummary,
                handoffShareChecklistNextAction,
                handoffShareCenterStatus,
                handoffShareCenterSummary,
                handoffShareCenterNextAction,
                handoffShareCenterDownloadActions,
                false,
                null,
                null,
                null,
                null,
                "MISSING",
                false,
                "No delivery receipt has been recorded for the current handoff package.",
                DemoReadinessStatus.NEEDS_ATTENTION,
                false,
                "Demo handoff package is send-ready but final delivery evidence is not current.",
                "Send the current handoff package, record a delivery receipt, then download the finalization report.",
                "MISSING",
                false,
                null,
                generatedAt,
                nextActions
        );
    }

    public DemoEvidenceBundleVo(
            DemoReadinessStatus status,
            String summary,
            DemoEvidenceBundleSummaryVo summaryCounts,
            DemoReadinessVo readiness,
            DemoSmokeChecklistVo smokeChecklist,
            ConfigurationSummaryVo configuration,
            DemoAdapterFixtureEvidenceVo adapterFixtures,
            FixTaskQueueSummaryVo queueSummary,
            FixTaskVo recentTask,
            String recentPullRequestUrl,
            GitHubWebhookSetupReadinessVo webhookSetupReadiness,
            WebhookDeliveryDiagnosticVo latestWebhookDelivery,
            List<WebhookDeliveryDiagnosticVo> recentWebhookDeliveries,
            RejectedTriggerAuditSummaryVo rejectedTriggerSummary,
            long activeQuarantineCount,
            DemoReadinessStatus handoffShareChecklistStatus,
            String handoffShareChecklistSummary,
            String handoffShareChecklistNextAction,
            DemoReadinessStatus handoffShareCenterStatus,
            String handoffShareCenterSummary,
            String handoffShareCenterNextAction,
            List<String> handoffShareCenterDownloadActions,
            boolean handoffShareDeliveryReceiptRecorded,
            String handoffShareLatestDeliveryReceiptId,
            String handoffShareLatestDeliveryTarget,
            String handoffShareLatestDeliveryChannel,
            String handoffShareLatestDeliveredAt,
            Instant generatedAt,
            List<String> nextActions
    ) {
        this(
                status,
                summary,
                summaryCounts,
                readiness,
                smokeChecklist,
                configuration,
                adapterFixtures,
                queueSummary,
                recentTask,
                recentPullRequestUrl,
                webhookSetupReadiness,
                latestWebhookDelivery,
                recentWebhookDeliveries,
                rejectedTriggerSummary,
                activeQuarantineCount,
                handoffShareChecklistStatus,
                handoffShareChecklistSummary,
                handoffShareChecklistNextAction,
                handoffShareCenterStatus,
                handoffShareCenterSummary,
                handoffShareCenterNextAction,
                handoffShareCenterDownloadActions,
                handoffShareDeliveryReceiptRecorded,
                handoffShareLatestDeliveryReceiptId,
                handoffShareLatestDeliveryTarget,
                handoffShareLatestDeliveryChannel,
                handoffShareLatestDeliveredAt,
                handoffShareDeliveryReceiptRecorded ? "FRESH" : "MISSING",
                handoffShareDeliveryReceiptRecorded,
                handoffShareDeliveryReceiptRecorded
                        ? "Latest delivery receipt matches the current handoff archive and session."
                        : "No delivery receipt has been recorded for the current handoff package.",
                handoffShareDeliveryReceiptRecorded ? DemoReadinessStatus.READY : DemoReadinessStatus.NEEDS_ATTENTION,
                handoffShareDeliveryReceiptRecorded,
                handoffShareDeliveryReceiptRecorded
                        ? "Demo handoff is finalized with a fresh delivery receipt for the current archive."
                        : "Demo handoff package is send-ready but final delivery evidence is not current.",
                handoffShareDeliveryReceiptRecorded
                        ? "Use the finalization report as the post-demo delivery acceptance record."
                        : "Send the current handoff package, record a delivery receipt, then download the finalization report.",
                handoffShareDeliveryReceiptRecorded ? "FRESH" : "MISSING",
                handoffShareDeliveryReceiptRecorded,
                handoffShareLatestDeliveryReceiptId,
                generatedAt,
                nextActions
        );
    }
}
