package io.patchpilot.backend.demo.domain;

import io.patchpilot.backend.configuration.ConfigurationSummaryVo;
import io.patchpilot.backend.github.credential.domain.GitHubWebhookSetupReadinessVo;
import io.patchpilot.backend.github.webhook.domain.WebhookDeliveryDiagnosticVo;
import io.patchpilot.backend.safety.domain.RejectedTriggerAuditSummaryVo;
import io.patchpilot.backend.task.domain.vo.FixTaskQueueSummaryVo;
import io.patchpilot.backend.task.domain.vo.FixTaskVo;

import java.time.Instant;
import java.util.List;

public record DemoEvidenceBundleVo(
        DemoReadinessStatus status,
        String summary,
        DemoEvidenceBundleSummaryVo summaryCounts,
        DemoReadinessVo readiness,
        DemoSmokeChecklistVo smokeChecklist,
        ConfigurationSummaryVo configuration,
        DemoAdapterFixtureEvidenceVo adapterFixtures,
        DemoEvaluationRunReadinessEvidenceVo evaluationRunReadiness,
        FixTaskQueueSummaryVo queueSummary,
        FixTaskVo recentTask,
        String recentPullRequestUrl,
        GitHubWebhookSetupReadinessVo webhookSetupReadiness,
        WebhookDeliveryDiagnosticVo latestWebhookDelivery,
        List<WebhookDeliveryDiagnosticVo> recentWebhookDeliveries,
        RejectedTriggerAuditSummaryVo rejectedTriggerSummary,
        long activeQuarantineCount,
        DemoReadinessStatus handoffShareChecklistStatus,
        String handoffShareChecklistSummary,
        String handoffShareChecklistNextAction,
        DemoReadinessStatus handoffShareCenterStatus,
        String handoffShareCenterSummary,
        String handoffShareCenterNextAction,
        List<String> handoffShareCenterDownloadActions,
        String launchEvidenceShareCenterStatus,
        boolean launchEvidenceShareCenterReady,
        String launchEvidenceShareCenterSummary,
        String launchEvidenceShareCenterNextAction,
        int launchEvidenceShareCenterArchiveCount,
        String launchEvidenceShareCenterLatestArchiveId,
        String launchEvidenceShareCenterLatestSessionId,
        String launchEvidenceShareCenterLatestPullRequestUrl,
        List<String> launchEvidenceShareCenterDownloadActions,
        DemoReadinessStatus launchEvidenceFinalizationStatus,
        boolean launchEvidenceFinalized,
        String launchEvidenceFinalizationSummary,
        String launchEvidenceFinalizationNextAction,
        String launchEvidenceFinalizationDeliveryReceiptFreshness,
        boolean launchEvidenceFinalizationDeliveryReceiptFresh,
        String launchEvidenceFinalizationLatestDeliveryReceiptId,
        DemoLaunchAcceptanceCloseoutEvidenceVo launchAcceptanceCloseoutEvidence,
        DemoLaunchAcceptanceCertificateEvidenceVo launchAcceptanceCertificateEvidence,
        DemoTaskEvidenceAcceptanceCertificateEvidenceVo taskEvidenceAcceptanceCertificateEvidence,
        DemoFinalHandoffReportPackageArchiveEvidenceVo finalHandoffReportPackageArchiveEvidence,
        DemoFinalAcceptanceShareFinalizationVo finalAcceptanceShareFinalization,
        DemoFinalAcceptanceCompletionCloseoutVo finalAcceptanceCompletionCloseoutEvidence,
        DemoFinalAcceptanceCompletionCloseoutArchiveEvidenceVo finalAcceptanceCompletionCloseoutArchiveEvidence,
        DemoFinalExternalReviewEvidencePackageVo finalExternalReviewEvidencePackage,
        DemoFinalExternalReviewEvidencePackageArchiveEvidenceVo finalExternalReviewEvidencePackageArchiveEvidence,
        boolean handoffShareDeliveryReceiptRecorded,
        String handoffShareLatestDeliveryReceiptId,
        String handoffShareLatestDeliveryTarget,
        String handoffShareLatestDeliveryChannel,
        String handoffShareLatestDeliveredAt,
        String handoffShareDeliveryReceiptFreshness,
        boolean handoffShareDeliveryReceiptFresh,
        String handoffShareDeliveryReceiptFreshnessSummary,
        DemoReadinessStatus handoffFinalizationStatus,
        boolean handoffFinalized,
        String handoffFinalizationSummary,
        String handoffFinalizationNextAction,
        String handoffFinalizationDeliveryReceiptFreshness,
        boolean handoffFinalizationDeliveryReceiptFresh,
        String handoffFinalizationLatestDeliveryReceiptId,
        Instant generatedAt,
        List<String> nextActions
) {
    public DemoEvidenceBundleVo(
            DemoReadinessStatus status,
            String summary,
            DemoEvidenceBundleSummaryVo summaryCounts,
            DemoReadinessVo readiness,
            DemoSmokeChecklistVo smokeChecklist,
            ConfigurationSummaryVo configuration,
            DemoAdapterFixtureEvidenceVo adapterFixtures,
            DemoEvaluationRunReadinessEvidenceVo evaluationRunReadiness,
            FixTaskQueueSummaryVo queueSummary,
            FixTaskVo recentTask,
            String recentPullRequestUrl,
            GitHubWebhookSetupReadinessVo webhookSetupReadiness,
            WebhookDeliveryDiagnosticVo latestWebhookDelivery,
            List<WebhookDeliveryDiagnosticVo> recentWebhookDeliveries,
            RejectedTriggerAuditSummaryVo rejectedTriggerSummary,
            long activeQuarantineCount,
            DemoReadinessStatus handoffShareChecklistStatus,
            String handoffShareChecklistSummary,
            String handoffShareChecklistNextAction,
            DemoReadinessStatus handoffShareCenterStatus,
            String handoffShareCenterSummary,
            String handoffShareCenterNextAction,
            List<String> handoffShareCenterDownloadActions,
            String launchEvidenceShareCenterStatus,
            boolean launchEvidenceShareCenterReady,
            String launchEvidenceShareCenterSummary,
            String launchEvidenceShareCenterNextAction,
            int launchEvidenceShareCenterArchiveCount,
            String launchEvidenceShareCenterLatestArchiveId,
            String launchEvidenceShareCenterLatestSessionId,
            String launchEvidenceShareCenterLatestPullRequestUrl,
            List<String> launchEvidenceShareCenterDownloadActions,
            DemoReadinessStatus launchEvidenceFinalizationStatus,
            boolean launchEvidenceFinalized,
            String launchEvidenceFinalizationSummary,
            String launchEvidenceFinalizationNextAction,
            String launchEvidenceFinalizationDeliveryReceiptFreshness,
            boolean launchEvidenceFinalizationDeliveryReceiptFresh,
            String launchEvidenceFinalizationLatestDeliveryReceiptId,
            DemoLaunchAcceptanceCloseoutEvidenceVo launchAcceptanceCloseoutEvidence,
            DemoLaunchAcceptanceCertificateEvidenceVo launchAcceptanceCertificateEvidence,
            DemoTaskEvidenceAcceptanceCertificateEvidenceVo taskEvidenceAcceptanceCertificateEvidence,
            DemoFinalHandoffReportPackageArchiveEvidenceVo finalHandoffReportPackageArchiveEvidence,
            DemoFinalAcceptanceShareFinalizationVo finalAcceptanceShareFinalization,
            DemoFinalAcceptanceCompletionCloseoutVo finalAcceptanceCompletionCloseoutEvidence,
            DemoFinalAcceptanceCompletionCloseoutArchiveEvidenceVo finalAcceptanceCompletionCloseoutArchiveEvidence,
            DemoFinalExternalReviewEvidencePackageVo finalExternalReviewEvidencePackage,
            boolean handoffShareDeliveryReceiptRecorded,
            String handoffShareLatestDeliveryReceiptId,
            String handoffShareLatestDeliveryTarget,
            String handoffShareLatestDeliveryChannel,
            String handoffShareLatestDeliveredAt,
            String handoffShareDeliveryReceiptFreshness,
            boolean handoffShareDeliveryReceiptFresh,
            String handoffShareDeliveryReceiptFreshnessSummary,
            DemoReadinessStatus handoffFinalizationStatus,
            boolean handoffFinalized,
            String handoffFinalizationSummary,
            String handoffFinalizationNextAction,
            String handoffFinalizationDeliveryReceiptFreshness,
            boolean handoffFinalizationDeliveryReceiptFresh,
            String handoffFinalizationLatestDeliveryReceiptId,
            Instant generatedAt,
            List<String> nextActions
    ) {
        this(
                status,
                summary,
                summaryCounts,
                readiness,
                smokeChecklist,
                configuration,
                adapterFixtures,
                evaluationRunReadiness,
                queueSummary,
                recentTask,
                recentPullRequestUrl,
                webhookSetupReadiness,
                latestWebhookDelivery,
                recentWebhookDeliveries,
                rejectedTriggerSummary,
                activeQuarantineCount,
                handoffShareChecklistStatus,
                handoffShareChecklistSummary,
                handoffShareChecklistNextAction,
                handoffShareCenterStatus,
                handoffShareCenterSummary,
                handoffShareCenterNextAction,
                handoffShareCenterDownloadActions,
                launchEvidenceShareCenterStatus,
                launchEvidenceShareCenterReady,
                launchEvidenceShareCenterSummary,
                launchEvidenceShareCenterNextAction,
                launchEvidenceShareCenterArchiveCount,
                launchEvidenceShareCenterLatestArchiveId,
                launchEvidenceShareCenterLatestSessionId,
                launchEvidenceShareCenterLatestPullRequestUrl,
                launchEvidenceShareCenterDownloadActions,
                launchEvidenceFinalizationStatus,
                launchEvidenceFinalized,
                launchEvidenceFinalizationSummary,
                launchEvidenceFinalizationNextAction,
                launchEvidenceFinalizationDeliveryReceiptFreshness,
                launchEvidenceFinalizationDeliveryReceiptFresh,
                launchEvidenceFinalizationLatestDeliveryReceiptId,
                launchAcceptanceCloseoutEvidence,
                launchAcceptanceCertificateEvidence,
                taskEvidenceAcceptanceCertificateEvidence,
                finalHandoffReportPackageArchiveEvidence,
                finalAcceptanceShareFinalization,
                finalAcceptanceCompletionCloseoutEvidence,
                finalAcceptanceCompletionCloseoutArchiveEvidence,
                finalExternalReviewEvidencePackage,
                DemoEvidenceBundleDefaults.missingFinalExternalReviewEvidencePackageArchiveEvidence(),
                handoffShareDeliveryReceiptRecorded,
                handoffShareLatestDeliveryReceiptId,
                handoffShareLatestDeliveryTarget,
                handoffShareLatestDeliveryChannel,
                handoffShareLatestDeliveredAt,
                handoffShareDeliveryReceiptFreshness,
                handoffShareDeliveryReceiptFresh,
                handoffShareDeliveryReceiptFreshnessSummary,
                handoffFinalizationStatus,
                handoffFinalized,
                handoffFinalizationSummary,
                handoffFinalizationNextAction,
                handoffFinalizationDeliveryReceiptFreshness,
                handoffFinalizationDeliveryReceiptFresh,
                handoffFinalizationLatestDeliveryReceiptId,
                generatedAt,
                nextActions
        );
    }

    public DemoEvidenceBundleVo(
            DemoReadinessStatus status,
            String summary,
            DemoEvidenceBundleSummaryVo summaryCounts,
            DemoReadinessVo readiness,
            DemoSmokeChecklistVo smokeChecklist,
            ConfigurationSummaryVo configuration,
            DemoAdapterFixtureEvidenceVo adapterFixtures,
            DemoEvaluationRunReadinessEvidenceVo evaluationRunReadiness,
            FixTaskQueueSummaryVo queueSummary,
            FixTaskVo recentTask,
            String recentPullRequestUrl,
            GitHubWebhookSetupReadinessVo webhookSetupReadiness,
            WebhookDeliveryDiagnosticVo latestWebhookDelivery,
            List<WebhookDeliveryDiagnosticVo> recentWebhookDeliveries,
            RejectedTriggerAuditSummaryVo rejectedTriggerSummary,
            long activeQuarantineCount,
            DemoReadinessStatus handoffShareChecklistStatus,
            String handoffShareChecklistSummary,
            String handoffShareChecklistNextAction,
            DemoReadinessStatus handoffShareCenterStatus,
            String handoffShareCenterSummary,
            String handoffShareCenterNextAction,
            List<String> handoffShareCenterDownloadActions,
            String launchEvidenceShareCenterStatus,
            boolean launchEvidenceShareCenterReady,
            String launchEvidenceShareCenterSummary,
            String launchEvidenceShareCenterNextAction,
            int launchEvidenceShareCenterArchiveCount,
            String launchEvidenceShareCenterLatestArchiveId,
            String launchEvidenceShareCenterLatestSessionId,
            String launchEvidenceShareCenterLatestPullRequestUrl,
            List<String> launchEvidenceShareCenterDownloadActions,
            DemoReadinessStatus launchEvidenceFinalizationStatus,
            boolean launchEvidenceFinalized,
            String launchEvidenceFinalizationSummary,
            String launchEvidenceFinalizationNextAction,
            String launchEvidenceFinalizationDeliveryReceiptFreshness,
            boolean launchEvidenceFinalizationDeliveryReceiptFresh,
            String launchEvidenceFinalizationLatestDeliveryReceiptId,
            DemoLaunchAcceptanceCloseoutEvidenceVo launchAcceptanceCloseoutEvidence,
            DemoLaunchAcceptanceCertificateEvidenceVo launchAcceptanceCertificateEvidence,
            DemoTaskEvidenceAcceptanceCertificateEvidenceVo taskEvidenceAcceptanceCertificateEvidence,
            DemoFinalHandoffReportPackageArchiveEvidenceVo finalHandoffReportPackageArchiveEvidence,
            DemoFinalAcceptanceShareFinalizationVo finalAcceptanceShareFinalization,
            boolean handoffShareDeliveryReceiptRecorded,
            String handoffShareLatestDeliveryReceiptId,
            String handoffShareLatestDeliveryTarget,
            String handoffShareLatestDeliveryChannel,
            String handoffShareLatestDeliveredAt,
            String handoffShareDeliveryReceiptFreshness,
            boolean handoffShareDeliveryReceiptFresh,
            String handoffShareDeliveryReceiptFreshnessSummary,
            DemoReadinessStatus handoffFinalizationStatus,
            boolean handoffFinalized,
            String handoffFinalizationSummary,
            String handoffFinalizationNextAction,
            String handoffFinalizationDeliveryReceiptFreshness,
            boolean handoffFinalizationDeliveryReceiptFresh,
            String handoffFinalizationLatestDeliveryReceiptId,
            Instant generatedAt,
            List<String> nextActions
    ) {
        this(
                status,
                summary,
                summaryCounts,
                readiness,
                smokeChecklist,
                configuration,
                adapterFixtures,
                evaluationRunReadiness,
                queueSummary,
                recentTask,
                recentPullRequestUrl,
                webhookSetupReadiness,
                latestWebhookDelivery,
                recentWebhookDeliveries,
                rejectedTriggerSummary,
                activeQuarantineCount,
                handoffShareChecklistStatus,
                handoffShareChecklistSummary,
                handoffShareChecklistNextAction,
                handoffShareCenterStatus,
                handoffShareCenterSummary,
                handoffShareCenterNextAction,
                handoffShareCenterDownloadActions,
                launchEvidenceShareCenterStatus,
                launchEvidenceShareCenterReady,
                launchEvidenceShareCenterSummary,
                launchEvidenceShareCenterNextAction,
                launchEvidenceShareCenterArchiveCount,
                launchEvidenceShareCenterLatestArchiveId,
                launchEvidenceShareCenterLatestSessionId,
                launchEvidenceShareCenterLatestPullRequestUrl,
                launchEvidenceShareCenterDownloadActions,
                launchEvidenceFinalizationStatus,
                launchEvidenceFinalized,
                launchEvidenceFinalizationSummary,
                launchEvidenceFinalizationNextAction,
                launchEvidenceFinalizationDeliveryReceiptFreshness,
                launchEvidenceFinalizationDeliveryReceiptFresh,
                launchEvidenceFinalizationLatestDeliveryReceiptId,
                launchAcceptanceCloseoutEvidence,
                launchAcceptanceCertificateEvidence,
                taskEvidenceAcceptanceCertificateEvidence,
                finalHandoffReportPackageArchiveEvidence,
                finalAcceptanceShareFinalization,
                DemoEvidenceBundleDefaults.missingFinalAcceptanceCompletionCloseoutEvidence(),
                DemoEvidenceBundleDefaults.missingFinalAcceptanceCompletionCloseoutArchiveEvidence(),
                DemoEvidenceBundleDefaults.missingFinalExternalReviewEvidencePackage(),
                handoffShareDeliveryReceiptRecorded,
                handoffShareLatestDeliveryReceiptId,
                handoffShareLatestDeliveryTarget,
                handoffShareLatestDeliveryChannel,
                handoffShareLatestDeliveredAt,
                handoffShareDeliveryReceiptFreshness,
                handoffShareDeliveryReceiptFresh,
                handoffShareDeliveryReceiptFreshnessSummary,
                handoffFinalizationStatus,
                handoffFinalized,
                handoffFinalizationSummary,
                handoffFinalizationNextAction,
                handoffFinalizationDeliveryReceiptFreshness,
                handoffFinalizationDeliveryReceiptFresh,
                handoffFinalizationLatestDeliveryReceiptId,
                generatedAt,
                nextActions
        );
    }

    public DemoEvidenceBundleVo(
            DemoReadinessStatus status,
            String summary,
            DemoEvidenceBundleSummaryVo summaryCounts,
            DemoReadinessVo readiness,
            DemoSmokeChecklistVo smokeChecklist,
            ConfigurationSummaryVo configuration,
            DemoAdapterFixtureEvidenceVo adapterFixtures,
            DemoEvaluationRunReadinessEvidenceVo evaluationRunReadiness,
            FixTaskQueueSummaryVo queueSummary,
            FixTaskVo recentTask,
            String recentPullRequestUrl,
            GitHubWebhookSetupReadinessVo webhookSetupReadiness,
            WebhookDeliveryDiagnosticVo latestWebhookDelivery,
            List<WebhookDeliveryDiagnosticVo> recentWebhookDeliveries,
            RejectedTriggerAuditSummaryVo rejectedTriggerSummary,
            long activeQuarantineCount,
            DemoReadinessStatus handoffShareChecklistStatus,
            String handoffShareChecklistSummary,
            String handoffShareChecklistNextAction,
            DemoReadinessStatus handoffShareCenterStatus,
            String handoffShareCenterSummary,
            String handoffShareCenterNextAction,
            List<String> handoffShareCenterDownloadActions,
            String launchEvidenceShareCenterStatus,
            boolean launchEvidenceShareCenterReady,
            String launchEvidenceShareCenterSummary,
            String launchEvidenceShareCenterNextAction,
            int launchEvidenceShareCenterArchiveCount,
            String launchEvidenceShareCenterLatestArchiveId,
            String launchEvidenceShareCenterLatestSessionId,
            String launchEvidenceShareCenterLatestPullRequestUrl,
            List<String> launchEvidenceShareCenterDownloadActions,
            DemoReadinessStatus launchEvidenceFinalizationStatus,
            boolean launchEvidenceFinalized,
            String launchEvidenceFinalizationSummary,
            String launchEvidenceFinalizationNextAction,
            String launchEvidenceFinalizationDeliveryReceiptFreshness,
            boolean launchEvidenceFinalizationDeliveryReceiptFresh,
            String launchEvidenceFinalizationLatestDeliveryReceiptId,
            DemoLaunchAcceptanceCloseoutEvidenceVo launchAcceptanceCloseoutEvidence,
            DemoLaunchAcceptanceCertificateEvidenceVo launchAcceptanceCertificateEvidence,
            DemoTaskEvidenceAcceptanceCertificateEvidenceVo taskEvidenceAcceptanceCertificateEvidence,
            DemoFinalHandoffReportPackageArchiveEvidenceVo finalHandoffReportPackageArchiveEvidence,
            boolean handoffShareDeliveryReceiptRecorded,
            String handoffShareLatestDeliveryReceiptId,
            String handoffShareLatestDeliveryTarget,
            String handoffShareLatestDeliveryChannel,
            String handoffShareLatestDeliveredAt,
            String handoffShareDeliveryReceiptFreshness,
            boolean handoffShareDeliveryReceiptFresh,
            String handoffShareDeliveryReceiptFreshnessSummary,
            DemoReadinessStatus handoffFinalizationStatus,
            boolean handoffFinalized,
            String handoffFinalizationSummary,
            String handoffFinalizationNextAction,
            String handoffFinalizationDeliveryReceiptFreshness,
            boolean handoffFinalizationDeliveryReceiptFresh,
            String handoffFinalizationLatestDeliveryReceiptId,
            Instant generatedAt,
            List<String> nextActions
    ) {
        this(
                status,
                summary,
                summaryCounts,
                readiness,
                smokeChecklist,
                configuration,
                adapterFixtures,
                evaluationRunReadiness,
                queueSummary,
                recentTask,
                recentPullRequestUrl,
                webhookSetupReadiness,
                latestWebhookDelivery,
                recentWebhookDeliveries,
                rejectedTriggerSummary,
                activeQuarantineCount,
                handoffShareChecklistStatus,
                handoffShareChecklistSummary,
                handoffShareChecklistNextAction,
                handoffShareCenterStatus,
                handoffShareCenterSummary,
                handoffShareCenterNextAction,
                handoffShareCenterDownloadActions,
                launchEvidenceShareCenterStatus,
                launchEvidenceShareCenterReady,
                launchEvidenceShareCenterSummary,
                launchEvidenceShareCenterNextAction,
                launchEvidenceShareCenterArchiveCount,
                launchEvidenceShareCenterLatestArchiveId,
                launchEvidenceShareCenterLatestSessionId,
                launchEvidenceShareCenterLatestPullRequestUrl,
                launchEvidenceShareCenterDownloadActions,
                launchEvidenceFinalizationStatus,
                launchEvidenceFinalized,
                launchEvidenceFinalizationSummary,
                launchEvidenceFinalizationNextAction,
                launchEvidenceFinalizationDeliveryReceiptFreshness,
                launchEvidenceFinalizationDeliveryReceiptFresh,
                launchEvidenceFinalizationLatestDeliveryReceiptId,
                launchAcceptanceCloseoutEvidence,
                launchAcceptanceCertificateEvidence,
                taskEvidenceAcceptanceCertificateEvidence,
                finalHandoffReportPackageArchiveEvidence,
                DemoEvidenceBundleDefaults.missingFinalAcceptanceShareFinalization(),
                DemoEvidenceBundleDefaults.missingFinalAcceptanceCompletionCloseoutEvidence(),
                DemoEvidenceBundleDefaults.missingFinalAcceptanceCompletionCloseoutArchiveEvidence(),
                DemoEvidenceBundleDefaults.missingFinalExternalReviewEvidencePackage(),
                handoffShareDeliveryReceiptRecorded,
                handoffShareLatestDeliveryReceiptId,
                handoffShareLatestDeliveryTarget,
                handoffShareLatestDeliveryChannel,
                handoffShareLatestDeliveredAt,
                handoffShareDeliveryReceiptFreshness,
                handoffShareDeliveryReceiptFresh,
                handoffShareDeliveryReceiptFreshnessSummary,
                handoffFinalizationStatus,
                handoffFinalized,
                handoffFinalizationSummary,
                handoffFinalizationNextAction,
                handoffFinalizationDeliveryReceiptFreshness,
                handoffFinalizationDeliveryReceiptFresh,
                handoffFinalizationLatestDeliveryReceiptId,
                generatedAt,
                nextActions
        );
    }

    public DemoEvidenceBundleVo(
            DemoReadinessStatus status,
            String summary,
            DemoEvidenceBundleSummaryVo summaryCounts,
            DemoReadinessVo readiness,
            DemoSmokeChecklistVo smokeChecklist,
            ConfigurationSummaryVo configuration,
            DemoAdapterFixtureEvidenceVo adapterFixtures,
            DemoEvaluationRunReadinessEvidenceVo evaluationRunReadiness,
            FixTaskQueueSummaryVo queueSummary,
            FixTaskVo recentTask,
            String recentPullRequestUrl,
            GitHubWebhookSetupReadinessVo webhookSetupReadiness,
            WebhookDeliveryDiagnosticVo latestWebhookDelivery,
            List<WebhookDeliveryDiagnosticVo> recentWebhookDeliveries,
            RejectedTriggerAuditSummaryVo rejectedTriggerSummary,
            long activeQuarantineCount,
            DemoReadinessStatus handoffShareChecklistStatus,
            String handoffShareChecklistSummary,
            String handoffShareChecklistNextAction,
            DemoReadinessStatus handoffShareCenterStatus,
            String handoffShareCenterSummary,
            String handoffShareCenterNextAction,
            List<String> handoffShareCenterDownloadActions,
            String launchEvidenceShareCenterStatus,
            boolean launchEvidenceShareCenterReady,
            String launchEvidenceShareCenterSummary,
            String launchEvidenceShareCenterNextAction,
            int launchEvidenceShareCenterArchiveCount,
            String launchEvidenceShareCenterLatestArchiveId,
            String launchEvidenceShareCenterLatestSessionId,
            String launchEvidenceShareCenterLatestPullRequestUrl,
            List<String> launchEvidenceShareCenterDownloadActions,
            DemoReadinessStatus launchEvidenceFinalizationStatus,
            boolean launchEvidenceFinalized,
            String launchEvidenceFinalizationSummary,
            String launchEvidenceFinalizationNextAction,
            String launchEvidenceFinalizationDeliveryReceiptFreshness,
            boolean launchEvidenceFinalizationDeliveryReceiptFresh,
            String launchEvidenceFinalizationLatestDeliveryReceiptId,
            DemoLaunchAcceptanceCloseoutEvidenceVo launchAcceptanceCloseoutEvidence,
            DemoLaunchAcceptanceCertificateEvidenceVo launchAcceptanceCertificateEvidence,
            DemoTaskEvidenceAcceptanceCertificateEvidenceVo taskEvidenceAcceptanceCertificateEvidence,
            boolean handoffShareDeliveryReceiptRecorded,
            String handoffShareLatestDeliveryReceiptId,
            String handoffShareLatestDeliveryTarget,
            String handoffShareLatestDeliveryChannel,
            String handoffShareLatestDeliveredAt,
            String handoffShareDeliveryReceiptFreshness,
            boolean handoffShareDeliveryReceiptFresh,
            String handoffShareDeliveryReceiptFreshnessSummary,
            DemoReadinessStatus handoffFinalizationStatus,
            boolean handoffFinalized,
            String handoffFinalizationSummary,
            String handoffFinalizationNextAction,
            String handoffFinalizationDeliveryReceiptFreshness,
            boolean handoffFinalizationDeliveryReceiptFresh,
            String handoffFinalizationLatestDeliveryReceiptId,
            Instant generatedAt,
            List<String> nextActions
    ) {
        this(
                status,
                summary,
                summaryCounts,
                readiness,
                smokeChecklist,
                configuration,
                adapterFixtures,
                evaluationRunReadiness,
                queueSummary,
                recentTask,
                recentPullRequestUrl,
                webhookSetupReadiness,
                latestWebhookDelivery,
                recentWebhookDeliveries,
                rejectedTriggerSummary,
                activeQuarantineCount,
                handoffShareChecklistStatus,
                handoffShareChecklistSummary,
                handoffShareChecklistNextAction,
                handoffShareCenterStatus,
                handoffShareCenterSummary,
                handoffShareCenterNextAction,
                handoffShareCenterDownloadActions,
                launchEvidenceShareCenterStatus,
                launchEvidenceShareCenterReady,
                launchEvidenceShareCenterSummary,
                launchEvidenceShareCenterNextAction,
                launchEvidenceShareCenterArchiveCount,
                launchEvidenceShareCenterLatestArchiveId,
                launchEvidenceShareCenterLatestSessionId,
                launchEvidenceShareCenterLatestPullRequestUrl,
                launchEvidenceShareCenterDownloadActions,
                launchEvidenceFinalizationStatus,
                launchEvidenceFinalized,
                launchEvidenceFinalizationSummary,
                launchEvidenceFinalizationNextAction,
                launchEvidenceFinalizationDeliveryReceiptFreshness,
                launchEvidenceFinalizationDeliveryReceiptFresh,
                launchEvidenceFinalizationLatestDeliveryReceiptId,
                launchAcceptanceCloseoutEvidence,
                launchAcceptanceCertificateEvidence,
                taskEvidenceAcceptanceCertificateEvidence,
                DemoEvidenceBundleDefaults.missingFinalHandoffReportPackageArchiveEvidence(),
                DemoEvidenceBundleDefaults.missingFinalAcceptanceShareFinalization(),
                DemoEvidenceBundleDefaults.missingFinalAcceptanceCompletionCloseoutEvidence(),
                DemoEvidenceBundleDefaults.missingFinalAcceptanceCompletionCloseoutArchiveEvidence(),
                DemoEvidenceBundleDefaults.missingFinalExternalReviewEvidencePackage(),
                handoffShareDeliveryReceiptRecorded,
                handoffShareLatestDeliveryReceiptId,
                handoffShareLatestDeliveryTarget,
                handoffShareLatestDeliveryChannel,
                handoffShareLatestDeliveredAt,
                handoffShareDeliveryReceiptFreshness,
                handoffShareDeliveryReceiptFresh,
                handoffShareDeliveryReceiptFreshnessSummary,
                handoffFinalizationStatus,
                handoffFinalized,
                handoffFinalizationSummary,
                handoffFinalizationNextAction,
                handoffFinalizationDeliveryReceiptFreshness,
                handoffFinalizationDeliveryReceiptFresh,
                handoffFinalizationLatestDeliveryReceiptId,
                generatedAt,
                nextActions
        );
    }

    public DemoEvidenceBundleVo(
            DemoReadinessStatus status,
            String summary,
            DemoEvidenceBundleSummaryVo summaryCounts,
            DemoReadinessVo readiness,
            DemoSmokeChecklistVo smokeChecklist,
            ConfigurationSummaryVo configuration,
            DemoAdapterFixtureEvidenceVo adapterFixtures,
            DemoEvaluationRunReadinessEvidenceVo evaluationRunReadiness,
            FixTaskQueueSummaryVo queueSummary,
            FixTaskVo recentTask,
            String recentPullRequestUrl,
            GitHubWebhookSetupReadinessVo webhookSetupReadiness,
            WebhookDeliveryDiagnosticVo latestWebhookDelivery,
            List<WebhookDeliveryDiagnosticVo> recentWebhookDeliveries,
            RejectedTriggerAuditSummaryVo rejectedTriggerSummary,
            long activeQuarantineCount,
            DemoReadinessStatus handoffShareChecklistStatus,
            String handoffShareChecklistSummary,
            String handoffShareChecklistNextAction,
            DemoReadinessStatus handoffShareCenterStatus,
            String handoffShareCenterSummary,
            String handoffShareCenterNextAction,
            List<String> handoffShareCenterDownloadActions,
            String launchEvidenceShareCenterStatus,
            boolean launchEvidenceShareCenterReady,
            String launchEvidenceShareCenterSummary,
            String launchEvidenceShareCenterNextAction,
            int launchEvidenceShareCenterArchiveCount,
            String launchEvidenceShareCenterLatestArchiveId,
            String launchEvidenceShareCenterLatestSessionId,
            String launchEvidenceShareCenterLatestPullRequestUrl,
            List<String> launchEvidenceShareCenterDownloadActions,
            DemoReadinessStatus launchEvidenceFinalizationStatus,
            boolean launchEvidenceFinalized,
            String launchEvidenceFinalizationSummary,
            String launchEvidenceFinalizationNextAction,
            String launchEvidenceFinalizationDeliveryReceiptFreshness,
            boolean launchEvidenceFinalizationDeliveryReceiptFresh,
            String launchEvidenceFinalizationLatestDeliveryReceiptId,
            DemoLaunchAcceptanceCloseoutEvidenceVo launchAcceptanceCloseoutEvidence,
            boolean handoffShareDeliveryReceiptRecorded,
            String handoffShareLatestDeliveryReceiptId,
            String handoffShareLatestDeliveryTarget,
            String handoffShareLatestDeliveryChannel,
            String handoffShareLatestDeliveredAt,
            String handoffShareDeliveryReceiptFreshness,
            boolean handoffShareDeliveryReceiptFresh,
            String handoffShareDeliveryReceiptFreshnessSummary,
            DemoReadinessStatus handoffFinalizationStatus,
            boolean handoffFinalized,
            String handoffFinalizationSummary,
            String handoffFinalizationNextAction,
            String handoffFinalizationDeliveryReceiptFreshness,
            boolean handoffFinalizationDeliveryReceiptFresh,
            String handoffFinalizationLatestDeliveryReceiptId,
            Instant generatedAt,
            List<String> nextActions
    ) {
        this(
                status,
                summary,
                summaryCounts,
                readiness,
                smokeChecklist,
                configuration,
                adapterFixtures,
                evaluationRunReadiness,
                queueSummary,
                recentTask,
                recentPullRequestUrl,
                webhookSetupReadiness,
                latestWebhookDelivery,
                recentWebhookDeliveries,
                rejectedTriggerSummary,
                activeQuarantineCount,
                handoffShareChecklistStatus,
                handoffShareChecklistSummary,
                handoffShareChecklistNextAction,
                handoffShareCenterStatus,
                handoffShareCenterSummary,
                handoffShareCenterNextAction,
                handoffShareCenterDownloadActions,
                launchEvidenceShareCenterStatus,
                launchEvidenceShareCenterReady,
                launchEvidenceShareCenterSummary,
                launchEvidenceShareCenterNextAction,
                launchEvidenceShareCenterArchiveCount,
                launchEvidenceShareCenterLatestArchiveId,
                launchEvidenceShareCenterLatestSessionId,
                launchEvidenceShareCenterLatestPullRequestUrl,
                launchEvidenceShareCenterDownloadActions,
                launchEvidenceFinalizationStatus,
                launchEvidenceFinalized,
                launchEvidenceFinalizationSummary,
                launchEvidenceFinalizationNextAction,
                launchEvidenceFinalizationDeliveryReceiptFreshness,
                launchEvidenceFinalizationDeliveryReceiptFresh,
                launchEvidenceFinalizationLatestDeliveryReceiptId,
                launchAcceptanceCloseoutEvidence,
                DemoEvidenceBundleDefaults.missingLaunchAcceptanceCertificateEvidence(),
                DemoEvidenceBundleDefaults.missingTaskEvidenceAcceptanceCertificateEvidence(),
                DemoEvidenceBundleDefaults.missingFinalHandoffReportPackageArchiveEvidence(),
                DemoEvidenceBundleDefaults.missingFinalAcceptanceShareFinalization(),
                DemoEvidenceBundleDefaults.missingFinalAcceptanceCompletionCloseoutEvidence(),
                DemoEvidenceBundleDefaults.missingFinalAcceptanceCompletionCloseoutArchiveEvidence(),
                DemoEvidenceBundleDefaults.missingFinalExternalReviewEvidencePackage(),
                handoffShareDeliveryReceiptRecorded,
                handoffShareLatestDeliveryReceiptId,
                handoffShareLatestDeliveryTarget,
                handoffShareLatestDeliveryChannel,
                handoffShareLatestDeliveredAt,
                handoffShareDeliveryReceiptFreshness,
                handoffShareDeliveryReceiptFresh,
                handoffShareDeliveryReceiptFreshnessSummary,
                handoffFinalizationStatus,
                handoffFinalized,
                handoffFinalizationSummary,
                handoffFinalizationNextAction,
                handoffFinalizationDeliveryReceiptFreshness,
                handoffFinalizationDeliveryReceiptFresh,
                handoffFinalizationLatestDeliveryReceiptId,
                generatedAt,
                nextActions
        );
    }

    public DemoEvidenceBundleVo(
            DemoReadinessStatus status,
            String summary,
            DemoEvidenceBundleSummaryVo summaryCounts,
            DemoReadinessVo readiness,
            DemoSmokeChecklistVo smokeChecklist,
            ConfigurationSummaryVo configuration,
            DemoAdapterFixtureEvidenceVo adapterFixtures,
            DemoEvaluationRunReadinessEvidenceVo evaluationRunReadiness,
            FixTaskQueueSummaryVo queueSummary,
            FixTaskVo recentTask,
            String recentPullRequestUrl,
            GitHubWebhookSetupReadinessVo webhookSetupReadiness,
            WebhookDeliveryDiagnosticVo latestWebhookDelivery,
            List<WebhookDeliveryDiagnosticVo> recentWebhookDeliveries,
            RejectedTriggerAuditSummaryVo rejectedTriggerSummary,
            long activeQuarantineCount,
            DemoReadinessStatus handoffShareChecklistStatus,
            String handoffShareChecklistSummary,
            String handoffShareChecklistNextAction,
            DemoReadinessStatus handoffShareCenterStatus,
            String handoffShareCenterSummary,
            String handoffShareCenterNextAction,
            List<String> handoffShareCenterDownloadActions,
            String launchEvidenceShareCenterStatus,
            boolean launchEvidenceShareCenterReady,
            String launchEvidenceShareCenterSummary,
            String launchEvidenceShareCenterNextAction,
            int launchEvidenceShareCenterArchiveCount,
            String launchEvidenceShareCenterLatestArchiveId,
            String launchEvidenceShareCenterLatestSessionId,
            String launchEvidenceShareCenterLatestPullRequestUrl,
            List<String> launchEvidenceShareCenterDownloadActions,
            DemoReadinessStatus launchEvidenceFinalizationStatus,
            boolean launchEvidenceFinalized,
            String launchEvidenceFinalizationSummary,
            String launchEvidenceFinalizationNextAction,
            String launchEvidenceFinalizationDeliveryReceiptFreshness,
            boolean launchEvidenceFinalizationDeliveryReceiptFresh,
            String launchEvidenceFinalizationLatestDeliveryReceiptId,
            boolean handoffShareDeliveryReceiptRecorded,
            String handoffShareLatestDeliveryReceiptId,
            String handoffShareLatestDeliveryTarget,
            String handoffShareLatestDeliveryChannel,
            String handoffShareLatestDeliveredAt,
            String handoffShareDeliveryReceiptFreshness,
            boolean handoffShareDeliveryReceiptFresh,
            String handoffShareDeliveryReceiptFreshnessSummary,
            DemoReadinessStatus handoffFinalizationStatus,
            boolean handoffFinalized,
            String handoffFinalizationSummary,
            String handoffFinalizationNextAction,
            String handoffFinalizationDeliveryReceiptFreshness,
            boolean handoffFinalizationDeliveryReceiptFresh,
            String handoffFinalizationLatestDeliveryReceiptId,
            Instant generatedAt,
            List<String> nextActions
    ) {
        this(
                status,
                summary,
                summaryCounts,
                readiness,
                smokeChecklist,
                configuration,
                adapterFixtures,
                evaluationRunReadiness,
                queueSummary,
                recentTask,
                recentPullRequestUrl,
                webhookSetupReadiness,
                latestWebhookDelivery,
                recentWebhookDeliveries,
                rejectedTriggerSummary,
                activeQuarantineCount,
                handoffShareChecklistStatus,
                handoffShareChecklistSummary,
                handoffShareChecklistNextAction,
                handoffShareCenterStatus,
                handoffShareCenterSummary,
                handoffShareCenterNextAction,
                handoffShareCenterDownloadActions,
                launchEvidenceShareCenterStatus,
                launchEvidenceShareCenterReady,
                launchEvidenceShareCenterSummary,
                launchEvidenceShareCenterNextAction,
                launchEvidenceShareCenterArchiveCount,
                launchEvidenceShareCenterLatestArchiveId,
                launchEvidenceShareCenterLatestSessionId,
                launchEvidenceShareCenterLatestPullRequestUrl,
                launchEvidenceShareCenterDownloadActions,
                launchEvidenceFinalizationStatus,
                launchEvidenceFinalized,
                launchEvidenceFinalizationSummary,
                launchEvidenceFinalizationNextAction,
                launchEvidenceFinalizationDeliveryReceiptFreshness,
                launchEvidenceFinalizationDeliveryReceiptFresh,
                launchEvidenceFinalizationLatestDeliveryReceiptId,
                DemoEvidenceBundleDefaults.missingLaunchAcceptanceCloseoutEvidence(),
                DemoEvidenceBundleDefaults.missingLaunchAcceptanceCertificateEvidence(),
                DemoEvidenceBundleDefaults.missingTaskEvidenceAcceptanceCertificateEvidence(),
                DemoEvidenceBundleDefaults.missingFinalHandoffReportPackageArchiveEvidence(),
                DemoEvidenceBundleDefaults.missingFinalAcceptanceShareFinalization(),
                DemoEvidenceBundleDefaults.missingFinalAcceptanceCompletionCloseoutEvidence(),
                DemoEvidenceBundleDefaults.missingFinalAcceptanceCompletionCloseoutArchiveEvidence(),
                DemoEvidenceBundleDefaults.missingFinalExternalReviewEvidencePackage(),
                handoffShareDeliveryReceiptRecorded,
                handoffShareLatestDeliveryReceiptId,
                handoffShareLatestDeliveryTarget,
                handoffShareLatestDeliveryChannel,
                handoffShareLatestDeliveredAt,
                handoffShareDeliveryReceiptFreshness,
                handoffShareDeliveryReceiptFresh,
                handoffShareDeliveryReceiptFreshnessSummary,
                handoffFinalizationStatus,
                handoffFinalized,
                handoffFinalizationSummary,
                handoffFinalizationNextAction,
                handoffFinalizationDeliveryReceiptFreshness,
                handoffFinalizationDeliveryReceiptFresh,
                handoffFinalizationLatestDeliveryReceiptId,
                generatedAt,
                nextActions
        );
    }

    public DemoEvidenceBundleVo(
            DemoReadinessStatus status,
            String summary,
            DemoEvidenceBundleSummaryVo summaryCounts,
            DemoReadinessVo readiness,
            DemoSmokeChecklistVo smokeChecklist,
            ConfigurationSummaryVo configuration,
            DemoAdapterFixtureEvidenceVo adapterFixtures,
            FixTaskQueueSummaryVo queueSummary,
            FixTaskVo recentTask,
            String recentPullRequestUrl,
            GitHubWebhookSetupReadinessVo webhookSetupReadiness,
            WebhookDeliveryDiagnosticVo latestWebhookDelivery,
            List<WebhookDeliveryDiagnosticVo> recentWebhookDeliveries,
            RejectedTriggerAuditSummaryVo rejectedTriggerSummary,
            long activeQuarantineCount,
            DemoReadinessStatus handoffShareChecklistStatus,
            String handoffShareChecklistSummary,
            String handoffShareChecklistNextAction,
            DemoReadinessStatus handoffShareCenterStatus,
            String handoffShareCenterSummary,
            String handoffShareCenterNextAction,
            List<String> handoffShareCenterDownloadActions,
            Instant generatedAt,
            List<String> nextActions
    ) {
        this(
                status,
                summary,
                summaryCounts,
                readiness,
                smokeChecklist,
                configuration,
                adapterFixtures,
                DemoEvidenceBundleDefaults.readyEvaluationRunReadiness(),
                queueSummary,
                recentTask,
                recentPullRequestUrl,
                webhookSetupReadiness,
                latestWebhookDelivery,
                recentWebhookDeliveries,
                rejectedTriggerSummary,
                activeQuarantineCount,
                handoffShareChecklistStatus,
                handoffShareChecklistSummary,
                handoffShareChecklistNextAction,
                handoffShareCenterStatus,
                handoffShareCenterSummary,
                handoffShareCenterNextAction,
                handoffShareCenterDownloadActions,
                DemoEvidenceBundleDefaults.launchEvidenceShareCenterStatus(),
                false,
                DemoEvidenceBundleDefaults.launchEvidenceShareCenterSummary(),
                DemoEvidenceBundleDefaults.launchEvidenceShareCenterNextAction(),
                0,
                null,
                null,
                null,
                List.of(),
                DemoReadinessStatus.NEEDS_ATTENTION,
                false,
                "Demo launch evidence package is not finalized for accepted delivery evidence.",
                "Archive launch evidence, share it, record a delivery receipt, then download the finalization report.",
                "MISSING",
                false,
                null,
                DemoEvidenceBundleDefaults.missingLaunchAcceptanceCloseoutEvidence(),
                DemoEvidenceBundleDefaults.missingLaunchAcceptanceCertificateEvidence(),
                DemoEvidenceBundleDefaults.missingTaskEvidenceAcceptanceCertificateEvidence(),
                DemoEvidenceBundleDefaults.missingFinalHandoffReportPackageArchiveEvidence(),
                DemoEvidenceBundleDefaults.missingFinalAcceptanceShareFinalization(),
                DemoEvidenceBundleDefaults.missingFinalAcceptanceCompletionCloseoutEvidence(),
                DemoEvidenceBundleDefaults.missingFinalAcceptanceCompletionCloseoutArchiveEvidence(),
                DemoEvidenceBundleDefaults.missingFinalExternalReviewEvidencePackage(),
                false,
                null,
                null,
                null,
                null,
                "MISSING",
                false,
                "No delivery receipt has been recorded for the current handoff package.",
                DemoReadinessStatus.NEEDS_ATTENTION,
                false,
                "Demo handoff package is send-ready but final delivery evidence is not current.",
                "Send the current handoff package, record a delivery receipt, then download the finalization report.",
                "MISSING",
                false,
                null,
                generatedAt,
                nextActions
        );
    }

    public DemoEvidenceBundleVo(
            DemoReadinessStatus status,
            String summary,
            DemoEvidenceBundleSummaryVo summaryCounts,
            DemoReadinessVo readiness,
            DemoSmokeChecklistVo smokeChecklist,
            ConfigurationSummaryVo configuration,
            DemoAdapterFixtureEvidenceVo adapterFixtures,
            DemoEvaluationRunReadinessEvidenceVo evaluationRunReadiness,
            FixTaskQueueSummaryVo queueSummary,
            FixTaskVo recentTask,
            String recentPullRequestUrl,
            GitHubWebhookSetupReadinessVo webhookSetupReadiness,
            WebhookDeliveryDiagnosticVo latestWebhookDelivery,
            List<WebhookDeliveryDiagnosticVo> recentWebhookDeliveries,
            RejectedTriggerAuditSummaryVo rejectedTriggerSummary,
            long activeQuarantineCount,
            DemoReadinessStatus handoffShareChecklistStatus,
            String handoffShareChecklistSummary,
            String handoffShareChecklistNextAction,
            DemoReadinessStatus handoffShareCenterStatus,
            String handoffShareCenterSummary,
            String handoffShareCenterNextAction,
            List<String> handoffShareCenterDownloadActions,
            boolean handoffShareDeliveryReceiptRecorded,
            String handoffShareLatestDeliveryReceiptId,
            String handoffShareLatestDeliveryTarget,
            String handoffShareLatestDeliveryChannel,
            String handoffShareLatestDeliveredAt,
            String handoffShareDeliveryReceiptFreshness,
            boolean handoffShareDeliveryReceiptFresh,
            String handoffShareDeliveryReceiptFreshnessSummary,
            DemoReadinessStatus handoffFinalizationStatus,
            boolean handoffFinalized,
            String handoffFinalizationSummary,
            String handoffFinalizationNextAction,
            String handoffFinalizationDeliveryReceiptFreshness,
            boolean handoffFinalizationDeliveryReceiptFresh,
            String handoffFinalizationLatestDeliveryReceiptId,
            Instant generatedAt,
            List<String> nextActions
    ) {
        this(
                status,
                summary,
                summaryCounts,
                readiness,
                smokeChecklist,
                configuration,
                adapterFixtures,
                evaluationRunReadiness,
                queueSummary,
                recentTask,
                recentPullRequestUrl,
                webhookSetupReadiness,
                latestWebhookDelivery,
                recentWebhookDeliveries,
                rejectedTriggerSummary,
                activeQuarantineCount,
                handoffShareChecklistStatus,
                handoffShareChecklistSummary,
                handoffShareChecklistNextAction,
                handoffShareCenterStatus,
                handoffShareCenterSummary,
                handoffShareCenterNextAction,
                handoffShareCenterDownloadActions,
                DemoEvidenceBundleDefaults.launchEvidenceShareCenterStatus(),
                false,
                DemoEvidenceBundleDefaults.launchEvidenceShareCenterSummary(),
                DemoEvidenceBundleDefaults.launchEvidenceShareCenterNextAction(),
                0,
                null,
                null,
                null,
                List.of(),
                DemoReadinessStatus.NEEDS_ATTENTION,
                false,
                "Demo launch evidence package is not finalized for accepted delivery evidence.",
                "Archive launch evidence, share it, record a delivery receipt, then download the finalization report.",
                "MISSING",
                false,
                null,
                DemoEvidenceBundleDefaults.missingLaunchAcceptanceCloseoutEvidence(),
                DemoEvidenceBundleDefaults.missingLaunchAcceptanceCertificateEvidence(),
                DemoEvidenceBundleDefaults.missingTaskEvidenceAcceptanceCertificateEvidence(),
                DemoEvidenceBundleDefaults.missingFinalHandoffReportPackageArchiveEvidence(),
                DemoEvidenceBundleDefaults.missingFinalAcceptanceShareFinalization(),
                DemoEvidenceBundleDefaults.missingFinalAcceptanceCompletionCloseoutEvidence(),
                DemoEvidenceBundleDefaults.missingFinalAcceptanceCompletionCloseoutArchiveEvidence(),
                DemoEvidenceBundleDefaults.missingFinalExternalReviewEvidencePackage(),
                handoffShareDeliveryReceiptRecorded,
                handoffShareLatestDeliveryReceiptId,
                handoffShareLatestDeliveryTarget,
                handoffShareLatestDeliveryChannel,
                handoffShareLatestDeliveredAt,
                handoffShareDeliveryReceiptFreshness,
                handoffShareDeliveryReceiptFresh,
                handoffShareDeliveryReceiptFreshnessSummary,
                handoffFinalizationStatus,
                handoffFinalized,
                handoffFinalizationSummary,
                handoffFinalizationNextAction,
                handoffFinalizationDeliveryReceiptFreshness,
                handoffFinalizationDeliveryReceiptFresh,
                handoffFinalizationLatestDeliveryReceiptId,
                generatedAt,
                nextActions
        );
    }

    public DemoEvidenceBundleVo(
            DemoReadinessStatus status,
            String summary,
            DemoEvidenceBundleSummaryVo summaryCounts,
            DemoReadinessVo readiness,
            DemoSmokeChecklistVo smokeChecklist,
            ConfigurationSummaryVo configuration,
            DemoAdapterFixtureEvidenceVo adapterFixtures,
            DemoEvaluationRunReadinessEvidenceVo evaluationRunReadiness,
            FixTaskQueueSummaryVo queueSummary,
            FixTaskVo recentTask,
            String recentPullRequestUrl,
            GitHubWebhookSetupReadinessVo webhookSetupReadiness,
            WebhookDeliveryDiagnosticVo latestWebhookDelivery,
            List<WebhookDeliveryDiagnosticVo> recentWebhookDeliveries,
            RejectedTriggerAuditSummaryVo rejectedTriggerSummary,
            long activeQuarantineCount,
            DemoReadinessStatus handoffShareChecklistStatus,
            String handoffShareChecklistSummary,
            String handoffShareChecklistNextAction,
            DemoReadinessStatus handoffShareCenterStatus,
            String handoffShareCenterSummary,
            String handoffShareCenterNextAction,
            List<String> handoffShareCenterDownloadActions,
            boolean handoffShareDeliveryReceiptRecorded,
            String handoffShareLatestDeliveryReceiptId,
            String handoffShareLatestDeliveryTarget,
            String handoffShareLatestDeliveryChannel,
            String handoffShareLatestDeliveredAt,
            Instant generatedAt,
            List<String> nextActions
    ) {
        this(
                status,
                summary,
                summaryCounts,
                readiness,
                smokeChecklist,
                configuration,
                adapterFixtures,
                evaluationRunReadiness,
                queueSummary,
                recentTask,
                recentPullRequestUrl,
                webhookSetupReadiness,
                latestWebhookDelivery,
                recentWebhookDeliveries,
                rejectedTriggerSummary,
                activeQuarantineCount,
                handoffShareChecklistStatus,
                handoffShareChecklistSummary,
                handoffShareChecklistNextAction,
                handoffShareCenterStatus,
                handoffShareCenterSummary,
                handoffShareCenterNextAction,
                handoffShareCenterDownloadActions,
                DemoEvidenceBundleDefaults.launchEvidenceShareCenterStatus(),
                false,
                DemoEvidenceBundleDefaults.launchEvidenceShareCenterSummary(),
                DemoEvidenceBundleDefaults.launchEvidenceShareCenterNextAction(),
                0,
                null,
                null,
                null,
                List.of(),
                DemoReadinessStatus.NEEDS_ATTENTION,
                false,
                "Demo launch evidence package is not finalized for accepted delivery evidence.",
                "Archive launch evidence, share it, record a delivery receipt, then download the finalization report.",
                "MISSING",
                false,
                null,
                DemoEvidenceBundleDefaults.missingLaunchAcceptanceCloseoutEvidence(),
                DemoEvidenceBundleDefaults.missingLaunchAcceptanceCertificateEvidence(),
                DemoEvidenceBundleDefaults.missingTaskEvidenceAcceptanceCertificateEvidence(),
                DemoEvidenceBundleDefaults.missingFinalHandoffReportPackageArchiveEvidence(),
                DemoEvidenceBundleDefaults.missingFinalAcceptanceShareFinalization(),
                DemoEvidenceBundleDefaults.missingFinalAcceptanceCompletionCloseoutEvidence(),
                DemoEvidenceBundleDefaults.missingFinalAcceptanceCompletionCloseoutArchiveEvidence(),
                DemoEvidenceBundleDefaults.missingFinalExternalReviewEvidencePackage(),
                handoffShareDeliveryReceiptRecorded,
                handoffShareLatestDeliveryReceiptId,
                handoffShareLatestDeliveryTarget,
                handoffShareLatestDeliveryChannel,
                handoffShareLatestDeliveredAt,
                handoffShareDeliveryReceiptRecorded ? "FRESH" : "MISSING",
                handoffShareDeliveryReceiptRecorded,
                handoffShareDeliveryReceiptRecorded
                        ? "Latest delivery receipt matches the current handoff archive and session."
                        : "No delivery receipt has been recorded for the current handoff package.",
                handoffShareDeliveryReceiptRecorded ? DemoReadinessStatus.READY : DemoReadinessStatus.NEEDS_ATTENTION,
                handoffShareDeliveryReceiptRecorded,
                handoffShareDeliveryReceiptRecorded
                        ? "Demo handoff is finalized with a fresh delivery receipt for the current archive."
                        : "Demo handoff package is send-ready but final delivery evidence is not current.",
                handoffShareDeliveryReceiptRecorded
                        ? "Use the finalization report as the post-demo delivery acceptance record."
                        : "Send the current handoff package, record a delivery receipt, then download the finalization report.",
                handoffShareDeliveryReceiptRecorded ? "FRESH" : "MISSING",
                handoffShareDeliveryReceiptRecorded,
                handoffShareLatestDeliveryReceiptId,
                generatedAt,
                nextActions
        );
    }

    public DemoEvidenceBundleVo(
            DemoReadinessStatus status,
            String summary,
            DemoEvidenceBundleSummaryVo summaryCounts,
            DemoReadinessVo readiness,
            DemoSmokeChecklistVo smokeChecklist,
            ConfigurationSummaryVo configuration,
            DemoAdapterFixtureEvidenceVo adapterFixtures,
            FixTaskQueueSummaryVo queueSummary,
            FixTaskVo recentTask,
            String recentPullRequestUrl,
            GitHubWebhookSetupReadinessVo webhookSetupReadiness,
            WebhookDeliveryDiagnosticVo latestWebhookDelivery,
            List<WebhookDeliveryDiagnosticVo> recentWebhookDeliveries,
            RejectedTriggerAuditSummaryVo rejectedTriggerSummary,
            long activeQuarantineCount,
            DemoReadinessStatus handoffShareChecklistStatus,
            String handoffShareChecklistSummary,
            String handoffShareChecklistNextAction,
            DemoReadinessStatus handoffShareCenterStatus,
            String handoffShareCenterSummary,
            String handoffShareCenterNextAction,
            List<String> handoffShareCenterDownloadActions,
            boolean handoffShareDeliveryReceiptRecorded,
            String handoffShareLatestDeliveryReceiptId,
            String handoffShareLatestDeliveryTarget,
            String handoffShareLatestDeliveryChannel,
            String handoffShareLatestDeliveredAt,
            Instant generatedAt,
            List<String> nextActions
    ) {
        this(
                status,
                summary,
                summaryCounts,
                readiness,
                smokeChecklist,
                configuration,
                adapterFixtures,
                DemoEvidenceBundleDefaults.readyEvaluationRunReadiness(),
                queueSummary,
                recentTask,
                recentPullRequestUrl,
                webhookSetupReadiness,
                latestWebhookDelivery,
                recentWebhookDeliveries,
                rejectedTriggerSummary,
                activeQuarantineCount,
                handoffShareChecklistStatus,
                handoffShareChecklistSummary,
                handoffShareChecklistNextAction,
                handoffShareCenterStatus,
                handoffShareCenterSummary,
                handoffShareCenterNextAction,
                handoffShareCenterDownloadActions,
                DemoEvidenceBundleDefaults.launchEvidenceShareCenterStatus(),
                false,
                DemoEvidenceBundleDefaults.launchEvidenceShareCenterSummary(),
                DemoEvidenceBundleDefaults.launchEvidenceShareCenterNextAction(),
                0,
                null,
                null,
                null,
                List.of(),
                DemoReadinessStatus.NEEDS_ATTENTION,
                false,
                "Demo launch evidence package is not finalized for accepted delivery evidence.",
                "Archive launch evidence, share it, record a delivery receipt, then download the finalization report.",
                "MISSING",
                false,
                null,
                DemoEvidenceBundleDefaults.missingLaunchAcceptanceCloseoutEvidence(),
                DemoEvidenceBundleDefaults.missingLaunchAcceptanceCertificateEvidence(),
                DemoEvidenceBundleDefaults.missingTaskEvidenceAcceptanceCertificateEvidence(),
                DemoEvidenceBundleDefaults.missingFinalHandoffReportPackageArchiveEvidence(),
                DemoEvidenceBundleDefaults.missingFinalAcceptanceShareFinalization(),
                DemoEvidenceBundleDefaults.missingFinalAcceptanceCompletionCloseoutEvidence(),
                DemoEvidenceBundleDefaults.missingFinalAcceptanceCompletionCloseoutArchiveEvidence(),
                DemoEvidenceBundleDefaults.missingFinalExternalReviewEvidencePackage(),
                handoffShareDeliveryReceiptRecorded,
                handoffShareLatestDeliveryReceiptId,
                handoffShareLatestDeliveryTarget,
                handoffShareLatestDeliveryChannel,
                handoffShareLatestDeliveredAt,
                handoffShareDeliveryReceiptRecorded ? "FRESH" : "MISSING",
                handoffShareDeliveryReceiptRecorded,
                handoffShareDeliveryReceiptRecorded
                        ? "Latest delivery receipt matches the current handoff archive and session."
                        : "No delivery receipt has been recorded for the current handoff package.",
                handoffShareDeliveryReceiptRecorded ? DemoReadinessStatus.READY : DemoReadinessStatus.NEEDS_ATTENTION,
                handoffShareDeliveryReceiptRecorded,
                handoffShareDeliveryReceiptRecorded
                        ? "Demo handoff is finalized with a fresh delivery receipt for the current archive."
                        : "Demo handoff package is send-ready but final delivery evidence is not current.",
                handoffShareDeliveryReceiptRecorded
                        ? "Use the finalization report as the post-demo delivery acceptance record."
                        : "Send the current handoff package, record a delivery receipt, then download the finalization report.",
                handoffShareDeliveryReceiptRecorded ? "FRESH" : "MISSING",
                handoffShareDeliveryReceiptRecorded,
                handoffShareLatestDeliveryReceiptId,
                generatedAt,
                nextActions
        );
    }

    public DemoEvidenceBundleVo(
            DemoReadinessStatus status,
            String summary,
            DemoEvidenceBundleSummaryVo summaryCounts,
            DemoReadinessVo readiness,
            DemoSmokeChecklistVo smokeChecklist,
            ConfigurationSummaryVo configuration,
            DemoAdapterFixtureEvidenceVo adapterFixtures,
            FixTaskQueueSummaryVo queueSummary,
            FixTaskVo recentTask,
            String recentPullRequestUrl,
            GitHubWebhookSetupReadinessVo webhookSetupReadiness,
            WebhookDeliveryDiagnosticVo latestWebhookDelivery,
            List<WebhookDeliveryDiagnosticVo> recentWebhookDeliveries,
            RejectedTriggerAuditSummaryVo rejectedTriggerSummary,
            long activeQuarantineCount,
            DemoReadinessStatus handoffShareChecklistStatus,
            String handoffShareChecklistSummary,
            String handoffShareChecklistNextAction,
            DemoReadinessStatus handoffShareCenterStatus,
            String handoffShareCenterSummary,
            String handoffShareCenterNextAction,
            List<String> handoffShareCenterDownloadActions,
            boolean handoffShareDeliveryReceiptRecorded,
            String handoffShareLatestDeliveryReceiptId,
            String handoffShareLatestDeliveryTarget,
            String handoffShareLatestDeliveryChannel,
            String handoffShareLatestDeliveredAt,
            String handoffShareDeliveryReceiptFreshness,
            boolean handoffShareDeliveryReceiptFresh,
            String handoffShareDeliveryReceiptFreshnessSummary,
            DemoReadinessStatus handoffFinalizationStatus,
            boolean handoffFinalized,
            String handoffFinalizationSummary,
            String handoffFinalizationNextAction,
            String handoffFinalizationDeliveryReceiptFreshness,
            boolean handoffFinalizationDeliveryReceiptFresh,
            String handoffFinalizationLatestDeliveryReceiptId,
            Instant generatedAt,
            List<String> nextActions
    ) {
        this(
                status,
                summary,
                summaryCounts,
                readiness,
                smokeChecklist,
                configuration,
                adapterFixtures,
                DemoEvidenceBundleDefaults.readyEvaluationRunReadiness(),
                queueSummary,
                recentTask,
                recentPullRequestUrl,
                webhookSetupReadiness,
                latestWebhookDelivery,
                recentWebhookDeliveries,
                rejectedTriggerSummary,
                activeQuarantineCount,
                handoffShareChecklistStatus,
                handoffShareChecklistSummary,
                handoffShareChecklistNextAction,
                handoffShareCenterStatus,
                handoffShareCenterSummary,
                handoffShareCenterNextAction,
                handoffShareCenterDownloadActions,
                DemoEvidenceBundleDefaults.launchEvidenceShareCenterStatus(),
                false,
                DemoEvidenceBundleDefaults.launchEvidenceShareCenterSummary(),
                DemoEvidenceBundleDefaults.launchEvidenceShareCenterNextAction(),
                0,
                null,
                null,
                null,
                List.of(),
                DemoReadinessStatus.NEEDS_ATTENTION,
                false,
                "Demo launch evidence package is not finalized for accepted delivery evidence.",
                "Archive launch evidence, share it, record a delivery receipt, then download the finalization report.",
                "MISSING",
                false,
                null,
                DemoEvidenceBundleDefaults.missingLaunchAcceptanceCloseoutEvidence(),
                DemoEvidenceBundleDefaults.missingLaunchAcceptanceCertificateEvidence(),
                DemoEvidenceBundleDefaults.missingTaskEvidenceAcceptanceCertificateEvidence(),
                DemoEvidenceBundleDefaults.missingFinalHandoffReportPackageArchiveEvidence(),
                DemoEvidenceBundleDefaults.missingFinalAcceptanceShareFinalization(),
                DemoEvidenceBundleDefaults.missingFinalAcceptanceCompletionCloseoutEvidence(),
                DemoEvidenceBundleDefaults.missingFinalAcceptanceCompletionCloseoutArchiveEvidence(),
                DemoEvidenceBundleDefaults.missingFinalExternalReviewEvidencePackage(),
                handoffShareDeliveryReceiptRecorded,
                handoffShareLatestDeliveryReceiptId,
                handoffShareLatestDeliveryTarget,
                handoffShareLatestDeliveryChannel,
                handoffShareLatestDeliveredAt,
                handoffShareDeliveryReceiptFreshness,
                handoffShareDeliveryReceiptFresh,
                handoffShareDeliveryReceiptFreshnessSummary,
                handoffFinalizationStatus,
                handoffFinalized,
                handoffFinalizationSummary,
                handoffFinalizationNextAction,
                handoffFinalizationDeliveryReceiptFreshness,
                handoffFinalizationDeliveryReceiptFresh,
                handoffFinalizationLatestDeliveryReceiptId,
                generatedAt,
                nextActions
        );
    }

    private static final class DemoEvidenceBundleDefaults {

        private static DemoEvaluationRunReadinessEvidenceVo readyEvaluationRunReadiness() {
            return new DemoEvaluationRunReadinessEvidenceVo(
                    DemoReadinessStatus.READY,
                    null,
                    null,
                    0,
                    0,
                    0,
                    List.of(),
                    List.of(),
                    List.of(),
                    "Evaluation run readiness summary reads archived full evaluation runs only; it does not create tasks, call the model, mutate Git, or write to GitHub.",
                    "Full evaluation run archive is ready; use it as current demo evidence."
            );
        }

        private static String launchEvidenceShareCenterStatus() {
            return "NO_ARCHIVE";
        }

        private static String launchEvidenceShareCenterSummary() {
            return "No archived launch evidence package is available for sharing.";
        }

        private static String launchEvidenceShareCenterNextAction() {
            return "Archive a final demo launch evidence package after a completed live run before sharing launch evidence.";
        }

        private static DemoLaunchAcceptanceCloseoutEvidenceVo missingLaunchAcceptanceCloseoutEvidence() {
            return new DemoLaunchAcceptanceCloseoutEvidenceVo(
                    DemoReadinessStatus.NEEDS_ATTENTION,
                    false,
                    false,
                    "No launch acceptance closeout archive is available.",
                    "Archive the final launch acceptance closeout after launch evidence is accepted.",
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    List.of("Archive the final launch acceptance closeout before using the evidence bundle as the launch record.")
            );
        }

        private static DemoLaunchAcceptanceCertificateEvidenceVo missingLaunchAcceptanceCertificateEvidence() {
            return new DemoLaunchAcceptanceCertificateEvidenceVo(
                    DemoReadinessStatus.NEEDS_ATTENTION,
                    false,
                    false,
                    "No launch acceptance certificate archive is available.",
                    "Archive the final launch acceptance certificate after the launch acceptance closeout is certified.",
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    List.of("Archive the final launch acceptance certificate before using the evidence bundle as the external-review launch record.")
            );
        }

        private static DemoTaskEvidenceAcceptanceCertificateEvidenceVo missingTaskEvidenceAcceptanceCertificateEvidence() {
            return new DemoTaskEvidenceAcceptanceCertificateEvidenceVo(
                    DemoReadinessStatus.NEEDS_ATTENTION,
                    false,
                    false,
                    "No task evidence acceptance certificate archive is available.",
                    "Archive a certified task evidence acceptance certificate after final task evidence closeout.",
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    List.of("Archive a task evidence acceptance certificate before using the evidence bundle as task-level review proof.")
            );
        }

        private static DemoFinalHandoffReportPackageArchiveEvidenceVo missingFinalHandoffReportPackageArchiveEvidence() {
            return new DemoFinalHandoffReportPackageArchiveEvidenceVo(
                    DemoReadinessStatus.NEEDS_ATTENTION,
                    false,
                    false,
                    "No final handoff report package archive is available.",
                    "Archive the final handoff report package after the post-demo handoff package is finalized.",
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    false,
                    null,
                    List.of("Archive the final handoff report package before using the evidence bundle as post-demo closeout proof.")
            );
        }

        private static DemoFinalAcceptanceShareFinalizationVo missingFinalAcceptanceShareFinalization() {
            return new DemoFinalAcceptanceShareFinalizationVo(
                    DemoReadinessStatus.NEEDS_ATTENTION,
                    false,
                    "Final acceptance share package is not finalized.",
                    "Archive and deliver the final acceptance share package before using the evidence bundle as external-review proof.",
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    "MISSING",
                    false,
                    "No delivery receipt has been recorded for the current final acceptance share package.",
                    List.of(new DemoFinalAcceptanceShareFinalizationVo.Check(
                            "Final acceptance delivery evidence",
                            DemoReadinessStatus.NEEDS_ATTENTION,
                            "No final acceptance delivery receipt is available.",
                            "Record a final acceptance delivery receipt."
                    )),
                    List.of("No final acceptance delivery evidence is available in the top-level evidence bundle."),
                    "# PatchPilot Final Demo Acceptance Share Finalization Gate",
                    Instant.EPOCH
            );
        }

        private static DemoFinalAcceptanceCompletionCloseoutVo missingFinalAcceptanceCompletionCloseoutEvidence() {
            return new DemoFinalAcceptanceCompletionCloseoutVo(
                    DemoReadinessStatus.NEEDS_ATTENTION,
                    false,
                    "Final acceptance completion closeout is not available.",
                    "Close the final acceptance completion delivery loop before using the evidence bundle as final external-review proof.",
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    "MISSING",
                    List.of(new DemoFinalAcceptanceCompletionCloseoutVo.Check(
                            "Final acceptance completion closeout",
                            DemoReadinessStatus.NEEDS_ATTENTION,
                            "No final acceptance completion closeout is available.",
                            "Generate the final acceptance completion closeout after completion evidence delivery is fresh."
                    )),
                    List.of("No final acceptance completion closeout evidence is available in the top-level evidence bundle."),
                    List.of("Download the final acceptance completion closeout after it reports READY."),
                    "GET /api/demo/evidence-bundle is read-only and does not mutate tasks, Git, or GitHub.",
                    "# PatchPilot Final Acceptance Completion Closeout\n",
                    Instant.EPOCH
            );
        }

        private static DemoFinalAcceptanceCompletionCloseoutArchiveEvidenceVo missingFinalAcceptanceCompletionCloseoutArchiveEvidence() {
            return new DemoFinalAcceptanceCompletionCloseoutArchiveEvidenceVo(
                    DemoReadinessStatus.NEEDS_ATTENTION,
                    false,
                    false,
                    "No final acceptance completion closeout archive is available.",
                    "Archive the final acceptance completion closeout after it is READY and closed.",
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    List.of("Archive the final acceptance completion closeout after it is READY and closed.")
            );
        }

        private static DemoFinalExternalReviewEvidencePackageVo missingFinalExternalReviewEvidencePackage() {
            return new DemoFinalExternalReviewEvidencePackageVo(
                    DemoReadinessStatus.NEEDS_ATTENTION,
                    false,
                    "Final external-review evidence package is not available in the top-level evidence bundle.",
                    "Load the final external-review evidence package before sharing demo evidence externally.",
                    DemoReadinessStatus.NEEDS_ATTENTION,
                    DemoReadinessStatus.NEEDS_ATTENTION,
                    DemoReadinessStatus.NEEDS_ATTENTION,
                    DemoReadinessStatus.NEEDS_ATTENTION,
                    DemoReadinessStatus.NEEDS_ATTENTION,
                    DemoReadinessStatus.NEEDS_ATTENTION,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    "MISSING",
                    null,
                    Instant.EPOCH,
                    List.of(new DemoFinalExternalReviewEvidencePackageVo.Check(
                            "Final external-review evidence package",
                            DemoReadinessStatus.NEEDS_ATTENTION,
                            "No final external-review package is available in this bundle.",
                            "Load the final external-review evidence package."
                    )),
                    List.of("No final external-review evidence package is available in the top-level evidence bundle."),
                    List.of("Download the final external-review evidence package after it reports READY."),
                    "GET /api/demo/evidence-bundle is read-only and does not mutate tasks, Git, or GitHub.",
                    "# PatchPilot Final External Review Evidence Package\n"
            );
        }

        private static DemoFinalExternalReviewEvidencePackageArchiveEvidenceVo
        missingFinalExternalReviewEvidencePackageArchiveEvidence() {
            return new DemoFinalExternalReviewEvidencePackageArchiveEvidenceVo(
                    DemoReadinessStatus.NEEDS_ATTENTION,
                    false,
                    false,
                    "No final external-review evidence package archive is available.",
                    "Archive the final external-review evidence package after it is READY.",
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    List.of("Archive the final external-review evidence package after it is READY.")
            );
        }
    }
}
